### ISSUE TITLE
Test Flow Fail: Install AFL (Linux)

### ISSUE THREAD

**Issue by IntelCaisui** [ccc-spdm-tools/spdm-rs#153]
.github\workflows\fuzz.yml

```
      - name: Install AFL (Linux)
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: install
          args: --force --version 0.12.17 afl
        if: runner.os == 'Linux'
```

While running cargo install --force --version 0.12.17 afl is conflict with current toolchain:

```
Caused by:
  rustc 1.80.0-nightly is not supported by the following package:
    home@0.5.11 requires rustc 1.81

```
Will firstly try to find a workable toolchain configuration while waiting for fixing.
